shared:
    image: node:18

jobs:
    main:
        requires: [~commit]
        steps:
            - start: echo ok
    join:
        requires: [sd@12753:sub]
        steps:
            - start: echo ok
