shared:
    image: node:18

jobs:
    A:
        requires: [~commit]
        steps:
            - start: echo ok
    B:
        requires: [~sd@12754:X]
        steps:
            - start: echo ok
    C:
        requires: [~sd@12754:Y]
        steps:
            - start: echo ok
